/////////////////////////////
// Generated by header-gen.sh
/////////////////////////////

#ifndef DATANAME_H
#define DATANAME_H

#define NUM_OF_NAMES 24

extern const char * const out_data_names[NUM_OF_NAMES + 1];

// fg output data names
#define FGDATA_VSI_FPM	"vsi-fpm"
#define FGDATA_ASI_KT	"asi-kt"
#define FGDATA_ALT_FT	"alt-ft"
#define FGDATA_ALT_INHG	"alt-inhg"
#define FGDATA_AI_PITCH	"ai-pitch"
#define FGDATA_AI_ROLL	"ai-roll"
#define FGDATA_AI_OFFSET	"ai-offset"
#define FGDATA_HI_HEADING	"hi-heading"
#define FGDATA_HI_HEADING_BUG_ERROR	"hi-heading-bug-error"
#define FGDATA_HI_BUG_OFFSET_DEG	"hi-bug-offset-deg"
#define FGDATA_HI_OFFSET_DEG	"hi-offset-deg"
#define FGDATA_TSI_TURN	"tsi-turn"
#define FGDATA_TSI_SLIP	"tsi-slip"
#define FGDATA_TSI_SPIN	"tsi-spin"
#define FGDATA_NAV_HAS_GS	"nav-has-gs"
#define FGDATA_NAV_IN_RANGE	"nav-in-range"
#define FGDATA_NAV_GS_IN_RANGE	"nav-gs-in-range"
#define FGDATA_NAV_FROM_FLAG	"nav-from-flag"
#define FGDATA_NAV_TO_FLAG	"nav-to-flag"
#define FGDATA_NAV_RADIAL_SELECTED_DEG	"nav-radial-selected-deg"
#define FGDATA_NAV_GS_DEFLECTION	"nav-gs-deflection"
#define FGDATA_NAV_HEADING_DEFLECTION	"nav-heading-deflection"
#define FGDATA_ENGINE_RPM	"engine-rpm"
#define FGDATA_ENGINE_RUNNING	"engine-running"
#define FGDATA_COMM_POWER_BUTTON	"comm-power-button"
#define FGDATA_COMM_VOLUME	"comm-volume"
#define FGDATA_COMM_SELECTED_MHZ	"comm-selected-mhz"
#define FGDATA_COMM_STANDBY_MHZ	"comm-standby-mhz"
#define FGDATA_COMM_SELECTED_MHZ_FMT	"comm-selected-mhz-fmt"
#define FGDATA_COMM_STANDBY_MHZ_FMT	"comm-standby-mhz-fmt"
#define FGDATA_NAV_VOLUME	"nav-volume"
#define FGDATA_NAV_SELECTED_MHZ	"nav-selected-mhz"
#define FGDATA_NAV_STANDBY_MHZ	"nav-standby-mhz"
#define FGDATA_NAV_SELECTED_MHZ_FMT	"nav-selected-mhz-fmt"
#define FGDATA_NAV_STANDBY_MHZ_FMT	"nav-standby-mhz-fmt"
#define FGDATA_DME_POWER_BUTTON	"dme-power-button"
#define FGDATA_DME_SWITCH_MIN_KTS	"dme-switch-min-kts"
#define FGDATA_DME_SWITCH_POSITION	"dme-switch-position"
#define FGDATA_DME_MILES_DISPLAY	"dme-miles-display"
#define FGDATA_DME_MIN_KTS_DISPLAY	"dme-min-kts-display"
#define FGDATA_DME_SOURCE	"dme-source"

#endif // DATANAME_H

