/////////////////////////////
// Generated by header-gen.sh
/////////////////////////////

#include <cstdlib>
#include "datanames.h"

// The order of the names in the array is important.
const char * const out_data_names[NUM_OF_NAMES + 1] = {
	"alt-inhg",
	"ai-offset",
	"hi-bug-offset-deg",
	"hi-offset-deg",
	"nav-radial-selected-deg",
	"1nav-radial-selected-deg",
	"comm-power-button",
	"comm-volume",
	"comm-selected-mhz",
	"comm-standby-mhz",
	"1comm-power-button",
	"1comm-volume",
	"1comm-selected-mhz",
	"1comm-standby-mhz",
	"nav-volume",
	"nav-selected-mhz",
	"nav-standby-mhz",
	"1nav-volume",
	"1nav-selected-mhz",
	"1nav-standby-mhz",
	"dme-power-button",
	"dme-switch-min-kts",
	"dme-switch-position",
	"dme-source",
	NULL
};

